### ISSUE TITLE
Add additional Opening

### ISSUE THREAD

**Issue by empeje** [kulkultech/open-source#100]
In the near future, we want to hire interns for
- Artificial Intelligence
- Machine Learning
- Blockchain
- Quantum Computing
- System Engineering

**Comment by Divyansh1011** [comment]
sure working on this need to include this in markdown right!!also i have exp with machine learning  :eyes:

**Comment by empeje** [comment]
Great, hardcore engineering is one of the long-term investments in our firm.  If you're interested in ML, we have a couple of real-world interns project open.

**Comment by empeje** [comment]
Solved in here https://github.com/kulkultech/open-source/pull/122
