### ISSUE TITLE
Add navigation for social media of Kulkul Tech

### ISSUE THREAD

**Issue by AhlOct** [kulkultech/open-source#102]
Its look like shortcut for social media owned by Kulkul Tech. Foregoing in navigation only discord navigation.

**Comment by empeje** [comment]
Hi @AhlOct thank you for your first issues.

Could you elaborate more on your suggestion? Are you saying that we need to add social media links in our open-source.kulkul.tech ?

**Comment by AhlOct** [comment]
Currently at open-source.kulkul.tech in the navigation section there are virtual interns, about and chat. In the chat section I want to replace it with a menu item that contains kulkul tech social media such as instagram, twitter, youtube etc. It is useful to know more in kulkul tech.

**Comment by empeje** [comment]
Interesting, please create a pull request to demonstrate your idea.

**Comment by empeje** [comment]
Solve #103
