### ISSUE TITLE
Adding social logo

### ISSUE THREAD

**Issue by AhlOct** [kulkultech/open-source#105]
I'm bored of seeing links go to social, that's why I added logo to make it more pleasing to the eye.

You can preview in this link : https://raw.githack.com/AhlOct/open-source/feature/Add-Social-Logo/index.html

**Comment by empeje** [comment]
Looks good. Please create a pull request.

**Comment by FatwaDwiHidayat** [comment]
Awesome ! We can quickly recognize social media just from the icon.

**Comment by empeje** [comment]
Solved in #108
