### ISSUE TITLE
Add to be FAQ about college student who can join

### ISSUE THREAD

**Issue by AhlOct** [kulkultech/open-source#106]
Which college student from major can join this internship?

**Comment by empeje** [comment]
Generally, no requirement, anyone in the world who just started their software engineering career can join. We have interns ranging from college student to career switcher (have years of experience but move to software engineering).

**Comment by aransafp** [comment]
Isn't this issue should be closed ? since the question already in FAQ.

**Comment by empeje** [comment]
Yes, we can close it.

Good catch @aransafp
