### ISSUE TITLE
Fix typo in internship.md

### ISSUE THREAD

**Issue by hopevd** [kulkultech/open-source#112]
there is typo in files internship.md line 218, **hot** it should be **how**

**Comment by empeje** [comment]
Good job on your first PR, could you please continue and create a pull request @xsaidahns?

**Comment by singgihbekti** [comment]
that's a good review @xsaidahns , in addition, I would like to propose a change in this part also where one of the sentences doesn't have a verb. The correction is able to be watched here: 
https://raw.githack.com/singgihbekti/open-source/feature/gh-pages-sb/en_ID/#!pages/internship.md#Step_7_-_Run_another_service_on_top_of_Docker

**Comment by empeje** [comment]
Solved in https://github.com/kulkultech/open-source/pull/116/
