### ISSUE TITLE
The improvement of the guidance

### ISSUE THREAD

**Issue by singgihbekti** [kulkultech/open-source#114]
In this case especially for step 5, in my perspective, it will be easier to be obtained by newcomers regarding 'upstream'.
The changes can be seen here: 
https://raw.githack.com/singgihbekti/open-source/gh-pages/en_ID/#!pages/internship.md#Step_5_-_Keeping_fork_updated

**Comment by empeje** [comment]
Solved in here https://github.com/kulkultech/open-source/pull/119/
