### ISSUE TITLE
Improvement by adding icon

### ISSUE THREAD

**Issue by singgihbekti** [kulkultech/open-source#118]
improvement by adding such icons to make it more interesting
the result of the improvement on index.md:
https://raw.githack.com/singgihbekti/open-source/feature/index-page/en_ID/#!index.md

**Comment by Divyansh1011** [comment]
this looks so nice!! make a PR looks good to me

**Comment by empeje** [comment]
Solved in here https://github.com/kulkultech/open-source/pull/117
