### ISSUE TITLE
Fix "step 5 - Keeping fork updated" format

### ISSUE THREAD

**Issue by aransafp** [kulkultech/open-source#129]
I saw the 1-step inside the bluebox, and the others(2&3) outside the bluebox. Is it on purpose ? which is the correct one ? all inside or outside the blubox

![image](https://user-images.githubusercontent.com/47907964/134799079-9be8b812-6b52-4a69-b394-70604bab5ce8.png)

**Comment by empeje** [comment]
Good catch, it is not intended, please write a PR for it.
