### ISSUE TITLE
Improve references structure in FAQ page

### ISSUE THREAD

**Issue by aransafp** [kulkultech/open-source#131]
I think the reference isn't well structure, really confusing and there is duplicate link. 

![image](https://user-images.githubusercontent.com/47907964/134865452-894f8de0-ab89-4028-bbc6-3334015fa982.png)

I have another approach:
- remove references section 
- create 2 new section from Github and Markdown
- improve leveling text
so it will help aspiring-intern to find the faq related to github/markdown

**Comment by empeje** [comment]
Thanks @aransafp. Please go ahead with the PR
