### ISSUE TITLE
About section directs to a wrong link

### ISSUE THREAD

**Issue by AlfredPros** [kulkultech/open-source#145]
When clicking the "About" button in navigation, it directs to https://www.kulkul.tech/about/, which is invalid.
It should be directed to https://www.kulkul.tech/about-us/ instead.

**Comment by cjj20** [comment]
I seem to have duplicated this issue as issue #155.

**Comment by empeje** [comment]
Thanks @cjj20 for your proactive initiative. This has been done in #146 and I merged it now :)
