### ISSUE TITLE
Create intern first steps progress tracker

### ISSUE THREAD

**Issue by empeje** [kulkultech/open-source#16]
Using the GitHub API we should be able to track how is the progress of the aspiring interns.

Here's the validation

- 5 merged pull requests (one at step 3, one at step 6, and three at step 8)
- 4 comments made on issues you didn't create (one at step 6 and three at step 8)
- 4 issues created (one at step 6 and three at step 8)

**Comment by galanggg** [comment]
for this issue, the interface is on the wiki ?

**Comment by empeje** [comment]
Yes on the wiki, just need to create a new page, and create a raw HTML with an id that you can manipulate using JavaScript.

**Comment by empeje** [comment]
This is resolved in #31
