### ISSUE TITLE
Add Discord Gif 

### ISSUE THREAD

**Issue by cjj20** [kulkultech/open-source#165]
Possibly add discord gif that leads to discord server somewhere on the homepage or internships first steps page.

Discord gif : https://cliply.co/wp-content/uploads/2021/08/372108630_DISCORD_LOGO_BLACK_400.gif

**Comment by empeje** [comment]
Interesting idea @cjj20 , we can try to do this

**Comment by cjj20** [comment]
> Interesting idea @cjj20 , we can try to do this

I added the discord gif

**Comment by empeje** [comment]
I think we can close this one @cjj20
