### ISSUE TITLE
Estimated numbers of intern

### ISSUE THREAD

**Issue by galanggg** [kulkultech/open-source#26]
need to be add in FAQ, to measure how much internship is needed

**Comment by empeje** [comment]
We have no strict limit on the number of interns we hire every year as our business is also growing. Everyone can prove they capable to join our internship if he proves able to finish the first steps and pass our interview.

@galanggg you can create a PR based on my answer above.

**Comment by galanggg** [comment]
@empeje thank you for the answer, and here my pr #27

**Comment by empeje** [comment]
Well done @galanggg. I'll close the issue.
