### ISSUE TITLE
The eligibility requirements for participation? #FAQ

### ISSUE THREAD

**Issue by galanggg** [kulkultech/open-source#28]
Are there any eligibility requirements to participate in the Kulkul internship?

**Comment by empeje** [comment]
Generally, there are no strict requirements. Anyone who early in their software engineering career can join this program as long as can commit a significant amount of time to this internship as I mention in the wiki. This internship program is intensive, so a time commitment is very important as this program is running virtually.

**Comment by galanggg** [comment]
thank you for the answer @empeje , so the point is there is no age limit or must / are currently studying to take part in this internship right?

**Comment by empeje** [comment]
Yes, there's no age limit and must currently in university/school. As long as they're early in their career anyone can join, but please keep in mind that this internship designed to accelerate junior engineers to be ready in the workplace and go to the next level in their career. So people with advanced skills are not encouraged to join but can apply to Kulkul as a full-time engineer.

**Comment by galanggg** [comment]
okay that's clear for me, thanks for you answers. And for this issue we need create a new FAQ ? or refer to this issue #26 ?

**Comment by empeje** [comment]
Just use this issue.

**Comment by empeje** [comment]
Solved in #29
