### ISSUE TITLE
Creating a Doc or FAQ for Github 

### ISSUE THREAD

**Issue by volkansahn** [kulkultech/open-source#45]
I have experienced some difficulties about Git commands. Also there are some procedure or method to write a git command like always create a new branch before making a pull request otherwise you will commit on your latest pull request(may be this is not true but I have experienced it.)

To summarize, it would be nice to write some small instructions  about the mostly used git commands.

**Comment by empeje** [comment]
Interesting idea, I think we can start working on it if you are interested in @volkansahn

**Comment by volkansahn** [comment]
Sure I will start to create document and then we will improve it in time.

**Comment by empeje** [comment]
Solved in #48
