### ISSUE TITLE
Documenting FAQ

### ISSUE THREAD

**Issue by empeje** [kulkultech/open-source#5]
If you have a question that can be considered as an FAQ you can share it here and with the issue and the PR that you proposed.

**Comment by galanggg** [comment]
Hello @empeje, maybe this is a frequently asked question. Should valid pull requests be merged? or just need to do pull requests? for `The Steps` section.

**Comment by empeje** [comment]
Can you give me more context about the issue? Are you referring to step 3, 6, and 8?

**Comment by galanggg** [comment]
For example, in step 3 we need to made a pull requests, does this pull request have to be merged first and then calculated as valid? or we just send the pull request and it counted as valid.

**Comment by empeje** [comment]
Pull request need to be merge except one in the Step 3.

**Comment by galanggg** [comment]
Okay @empeje thanks, that's pretty clear

**Comment by empeje** [comment]
Cool, you can also create a PR to add an FAQ about this issue.

**Comment by galanggg** [comment]
Sure, do you have a format for the questions and answers ?

**Comment by empeje** [comment]
no format yet, just a simple question-answer is enough @galanggg

**Comment by empeje** [comment]
Solved in #17 #27 #29 by @galanggg
