### ISSUE TITLE
Need tutorial on windows

### ISSUE THREAD

**Issue by HananAskarim** [kulkultech/open-source#64]
I think the step in this apprenticeship is very difficult, because there is no tutorial in the form of windows so that I who use the Windows operating system find it a little difficult because it is a little different from Mac OS in the video tutorial, where I have to look for further instructions from various reference sources so that takes more longer time even though it is only different or only a small error.

**Comment by empeje** [comment]
Hi @HananAskarim, thank you for creating your first issue.

I understand that our internship first page still needs improvement, but it is intentional so that our aspiring interns like you can help us fix it.

Here's my question, **what we can do differently to fix your issue so that the next aspiring interns who uses Windows can learn it easily?**

**Comment by HananAskarim** [comment]
For other participants who use windows to understand the steps, I think they need an example of the syntax for windows

**Comment by empeje** [comment]
> For other participants who use windows to understand the steps, I think they need an example of the syntax for windows

Could you please create MR for this proposal?

**Comment by HananAskarim** [comment]
I'll try to create a code document for windows in one of the steps in the video tutorial

**Comment by empeje** [comment]
Yes, please create Pull Request

---
Note:
I mentioned MR or merge request which is the same as pull request).

**Comment by FatwaDwiHidayat** [comment]
> I'll try to create a code document for windows in one of the steps in the video tutorial

For more details, maybe you can add screenshot image too.

**Comment by HananAskarim** [comment]
I had created a new Pull Request and I am adding a post in the FAQ on how to create SSH for windows

**Comment by HananAskarim** [comment]
> Yes, please create Pull Request
> 
> Note:
> I mentioned MR or merge request which is the same as pull request).

I had created a new Pull Request and I am adding a post in the FAQ on how to create SSH for windows
