### ISSUE TITLE
Improve user interface by change font color in Duration and Time

### ISSUE THREAD

**Issue by MuhammadAzka9** [kulkultech/open-source#65]
I think the user interface on the website of kulkul tech  is less attractive so that it causes users to sometimes have difficulty understanding.

**Comment by empeje** [comment]
Hi @MuhammadAzka9 , thank you for creating your first issue.

I understand that our internship first page still needs improvement, but it is intentional so that our aspiring interns like you can help us fix it.

About your concern, **what we can do differently to make our internship page more attractive? And what is the correlation of attractiveness in helping you understand the material?**

**Comment by MuhammadAzka9** [comment]
I mean at every step there is a note, in that note the font color and background are the same color, in my opinion it's not nice to look at

**Comment by empeje** [comment]
Could you please your concrete idea about how to make it better? Could you illustrate or create a Pull Request to change it?

**Comment by MuhammadAzka9** [comment]
I've changed the font color in the Duration and time notes to make it look more attractive, please review

**Comment by empeje** [comment]
Could you please elaborate on why you want to change the colour to red in this PR (https://github.com/kulkultech/open-source/pull/80)? 

We have established a pattern where the note has a blueish colour. See the image below for an example.

<img width="927" alt="Screen Shot 2021-04-26 at 09 29 42" src="https://user-images.githubusercontent.com/11813607/116021200-efd28a80-a671-11eb-8350-4ce3ffffbec6.png">

**Comment by MuhammadAzka9** [comment]
> Could you please elaborate on why you want to change the colour to red in this PR (#80)?
> 
> We have established a pattern where the note has a blueish colour. See the image below for an example.
> 
> <img alt="Screen Shot 2021-04-26 at 09 29 42" width="927" src="https://user-images.githubusercontent.com/11813607/116021200-efd28a80-a671-11eb-8350-4ce3ffffbec6.png">

**Comment by MuhammadAzka9** [comment]
i want to change the colour of font to red in this PR #80 because it is an important note and also the color is not the same as the background

**Comment by empeje** [comment]
We already have the Blue background for notes, can you change it to that instead.

See here for an example https://github.com/kulkultech/open-source/issues/65#issuecomment-826511787

**Comment by empeje** [comment]
Solved in #80
