### ISSUE TITLE
Add Subtitle to the Tutorial Video

### ISSUE THREAD

**Issue by FatwaDwiHidayat** [kulkultech/open-source#66]
I think the video tutorial is a bit difficult to understand because every person has vary skill of English. So we should add subtitles, doesn't have to be Bahasa Indonesia, but English subtitles are enough and very helpful because Kulkul Tech is based on International.

**Comment by empeje** [comment]
Hi @FatwaDwiHidayat, thank you for your first issues. You make a huge progress 🎉 

I think your issues is really good, right on the issue. **What is the best way to create subtitle or closed captions?**

**Comment by FatwaDwiHidayat** [comment]
Thanks for review my issue. This is just for efficiency measures to easily get the point in the video.
I would like subtitle because it really more helpful while I can read and also hear in same time. And also in the video, I was very helpful if there is an option to slow down the video speed. Because the video action and explanation in my opinion is sometimes too fast, so I have to repeat several times to get the point. I found an option to change the speed of the video but only to speed it up.

![image](https://user-images.githubusercontent.com/44151560/114356977-63b56300-9b9b-11eb-81c3-f803ee2cb3f9.png)

**Comment by empeje** [comment]
Sure, could you help us add subtitle to one of our video?

**Comment by galanggg** [comment]
That's will be great if each video has a subtitle :+1:

**Comment by FatwaDwiHidayat** [comment]
> Sure, could you help us add subtitle to one of our video?

Yes, sure. It is okay if I add a Hardsub ? Cause I haven't started to make softsub yet.

**Comment by FatwaDwiHidayat** [comment]
> That's will be great if each video has a subtitle 👍

Yeah, its really helpful for participants.

**Comment by empeje** [comment]
> Yes, sure. It is okay if I add a Hardsub ? Cause I haven't started to make softsub yet.

Let's start by creating a transcript (without the timeline) in a text file and upload it to the repository and have it as a link below the video.

**Comment by FatwaDwiHidayat** [comment]
I had already made the subtitle for **Step 5 Video**. I dont know this is good, but I had try my best with my ears. 
I will make subtitle for all the videos if I had officially accepted and joined the internship member.
My plan is to provide a subtitle download button on the internship page for each video.


Download the subtitle here : [[Subtitle] Step 5 - Keeping fork updated.zip](https://github.com/kulkultech/open-source/files/6301496/Subtitle.Step.5.-.Keeping.fork.updated.zip)

![image](https://user-images.githubusercontent.com/44151560/114502803-89537280-9c56-11eb-8b33-1914c2e54387.png)

**Comment by empeje** [comment]
Excellent, let me reupload the video to youtube and I'll give you the new link so you can create a PR for changing the video to the new link

**Comment by empeje** [comment]
Hi @FatwaDwiHidayat this is the updated link https://www.youtube.com/watch?v=XsG3meuxbGc with subtitle, you can create a pull request to change the old link with the new link.

**Comment by FatwaDwiHidayat** [comment]
Thank you, I'll make subtitle for other video soon.

**Comment by empeje** [comment]
Excellent, but first make sure you create the PR for the first video above.

**Comment by FatwaDwiHidayat** [comment]
I had already made the subtitle for Step 6 Video.

Here the subtitle : [[Subtitle] Step 6 - GitHub Issues Tutorial.zip](https://github.com/kulkultech/open-source/files/6321330/Subtitle.Step.6.-.GitHub.Issues.Tutorial.zip)

![image](https://user-images.githubusercontent.com/44151560/114943686-95b31780-9e70-11eb-9c7b-f3299010d43b.png)

**Comment by empeje** [comment]
Awesome, here's the new YouTube link https://www.youtube.com/watch?v=hPuMTRQ6cyw @FatwaDwiHidayat

**Comment by FatwaDwiHidayat** [comment]
I had already made the subtitle for Step 7 Video.

Here the subtitle : [Step 7 - Run another service on top of Docker.zip](https://github.com/kulkultech/open-source/files/6330597/Step.7.-.Run.another.service.on.top.of.Docker.zip)

![image](https://user-images.githubusercontent.com/44151560/115136422-dd40cb80-a049-11eb-9f29-74726a5ebbc0.png)

**Comment by empeje** [comment]
Cool, you can use the following video link for step 7 https://youtu.be/5Ms-GHowuzY

**Comment by empeje** [comment]
Solved in #67 #78 #75
