### ISSUE TITLE
Add New References About Markdown in FAQ

### ISSUE THREAD

**Issue by FatwaDwiHidayat** [kulkultech/open-source#76]
As a participant, I was a little confused because this is the first time using markdown. Usually using HTML for markup language. So it needs a little adjustment. After I learned more, it turned out that markdown had more advantages.

Because the internship website use .md, I add new references about Markdown, how to use it etc.
I hope this can help participants to fix issues and easily modify pages by understanding markdown more deeply.

**Comment by empeje** [comment]
What is the difference between the new markdown resources with the ones that already available on our site?

**Comment by FatwaDwiHidayat** [comment]
In my opinion, the video tutorial is also complete, but I added in references some more markdown examples and variations, differences with HTML in head-to-head, and also prohibitions using markdown such as "dont do this" because it doesn't work on markdown. Maybe it's like a summary which we can easily see and read at any time randomly.

**Comment by empeje** [comment]
Ah I see, is it related to https://github.com/kulkultech/open-source/pull/77 ?

**Comment by FatwaDwiHidayat** [comment]
Yes, I had created pull request about it too, thanks for merger.

**Comment by empeje** [comment]
I'll marked this issues as resolved.
