### ISSUE TITLE
Add photo frame in member photo

### ISSUE THREAD

**Issue by HananAskarim** [kulkultech/open-source#81]
I think it is necessary to add a frame to the photo because there is one member photo size that is not the same as the photo of other members

**Comment by FatwaDwiHidayat** [comment]
Yes, I agree. Because there is 1 member whose photo size is different from the others. Its too big. I try to fix it before, but not successful yet.

![image](https://user-images.githubusercontent.com/44151560/115947618-11f1ce80-a4f3-11eb-9f4b-4af59875fad1.png)

**Comment by empeje** [comment]
Thank you for creating another issue 🎉 

This is happening when we use the Github profile picture but the user doesn't have any profile picture yet in their Github account.

**Comment by HananAskarim** [comment]
I have fixed Ojas photo size to other members as in the image and made a Pull Request with my email.

![image](https://user-images.githubusercontent.com/44084593/115993298-63d24b80-a5fc-11eb-80d7-07dca3306d3e.png)

**Comment by empeje** [comment]
Nicely done.

Closed in https://github.com/kulkultech/open-source/pull/80
