### ISSUE TITLE
Create the note of Progress Tracker into bold

### ISSUE THREAD

**Issue by MuhammadAzka9** [kulkultech/open-source#90]
I would like to create the text in the Progress Tracker into bold, because it is clearly read by the members

**Comment by empeje** [comment]
Could you please illustrate? I think the progress tracker is clear enough for me 🤔

**Comment by MuhammadAzka9** [comment]
I think the text change into bold it will be more attention for the member to read this note
![prog](https://user-images.githubusercontent.com/44120264/116859903-e8d7e900-ac2a-11eb-8c71-78b348a97009.PNG)

**Comment by empeje** [comment]
I see, cool 🎉 

https://github.com/kulkultech/open-source/pull/91
