### ISSUE TITLE
Create tutorial adding new SSH key to Github account on Linux

### ISSUE THREAD

**Issue by MuhammadAzka9** [kulkultech/open-source#97]
In this case I will give a tutorial about adding new SSH key to Github account on Linux, and the tutorial on the FAQ page

**Comment by empeje** [comment]
We have the following https://open-source.kulkul.tech/en_ID/#!pages/faq.md. How does your proposal different from this one?

**Comment by MuhammadAzka9** [comment]
I think there are several different commands between Linux and another OS, for example on this picture, and also i have a new PR #98, please review ya..
![ssh](https://user-images.githubusercontent.com/44120264/117100172-455b1580-ad9d-11eb-8cf6-a6feab2df4c5.PNG)

**Comment by empeje** [comment]
Resolved in https://github.com/kulkultech/open-source/pull/98
